### ISSUE TITLE
active cases vs total recovered

### ISSUE THREAD

**Issue by meppydc** [iahuang/corona-py#4]
The columns have switched in the site I believe, this should be the new code.

`extract_int(cols[1]),`
`extract_int(cols[6]),`
`extract_int(cols[3]),`
 `extract_int(cols[5]),`
  `extract_int(cols[7]),`

**Comment by bitog** [comment]
Awesome thank you!

**Comment by iahuang** [comment]
Fixed in https://github.com/iahuang/corona-py/commit/0b2884ae212348df075296efb9553b35bf5967e5
